### ISSUE TITLE
`php-redis` package without explicit version

### ISSUE THREAD

**Issue by strarsis** [E-VANCE/trellis-redis#2]
The `php-redis` package is also specified [without an explicit version](https://github.com/E-VANCE/trellis-redis/blob/6c4a04c1e24a90d5831e310acb0be257bd7f9cc8/tasks/main.yml#L9-L13), 
this can result in PHP packages being installed for a different PHP version.
PR: https://github.com/E-VANCE/trellis-redis/pull/1

**Comment by E-VANCE** [comment]
Thanks for the issue and the PR – has been merged.
